import { Platform } from "models"

export const platforms: Platform[] = [
    {
        id: '3449qNq8',
        color: '#1A1A1A',
        label: 'Github',
        icon: '/github.svg',
        url: 'https://github.com/',
        example: 'CodeNinjaNoob', 
    },
    {
        id: '¿ew_n9lm',
        color: '#64CCDB',
        label: 'Frontend Mentor',
        icon: '/frontend-mentor.svg',
        url: 'https://www.frontendmentor.io/profile/',
        example: 'SelfieQueenSloth', 
    },
    {
        id: 'W(*066ZE',
        color: '#43B7E9',
        label: 'Twitter',
        icon: '/twitter.svg',
        url: 'https://twitter.com/',
        example: 'Troll79', 
    },
    {
        id: 'oDmXW7g4',
        color: '#1e1f26',
        label: 'Codepen',
        icon: '/codepen.svg',
        url: 'https://codepen.io/',
        example: 'DIYFailWizard', 
    },
    {
        id: 'FufenTbz',
        color: '#2D68FF',
        label: 'Linkedin',
        icon: '/linkedin.svg',
        url: 'https://www.linkedin.com/in/',
        example: 'NetworkingNinja', 
    },
    {
        id: 'r&X@9leO',
        color: '#EE3939',
        label: 'Youtube',
        icon: '/youtube.svg',
        url: 'https://www.youtube.com/',
        example: 'VideoGameGuru42', 
    },
    {
        id: 'E){CvID7',
        color: '#2442AC',
        label: 'Facebook',
        icon: '/facebook.svg',
        url: 'https://www.facebook.com/',
        example: 'CatMemeConnoisseur', 
    },
    {
        id: 'BLG136R|',
        color: '#9146ff',
        label: 'Twitch',
        icon: '/twitch.svg',
        url: 'https://www.twitch.tv/',
        example: 'GamerFailMaster', 
    },
    {
        id: 'PXa}OU;o',
        color: '#333',
        label: 'Dev.to',
        icon: '/devto.svg',
        url: 'https://dev.to/',
        example: 'CodeSarcasmWizard', 
    },
    {
        id: 'Z6LI2xRb',
        color: '#8A1A50',
        label: 'Codewars',
        icon: '/codewars.svg',
        url: 'https://www.codewars.com/users/',
        example: 'CodeWarriorNoob', 
    },
    {
        id: ']@q¡Mq1A',
        color: '#302267',
        label: 'Free Code Camp',
        icon: '/freecodecamp.svg',
        url: 'https://www.freecodecamp.org/',
        example: 'CodeCampSlacker', 
    },
    {
        id: '_9kHx6]&',
        color: '#EB4925',
        label: 'Gitlab',
        icon: '/gitlab.svg',
        url: 'https://gitlab.com/',
        example: 'GitLabGuruFail', 
    },
    {
        id: 'HuKFEvNw',
        color: '#0330D1',
        label: 'Hashnode',
        icon: '/hashnode.svg',
        url: 'https://hashnode.com/@',
        example: 'CodeBloggingClown', 
    },
    {
        id: 'X&Pvw&f1',
        color: '#EC7100',
        label: 'Stack Overflow',
        icon: '/stack-overflow.svg',
        url: 'https://stackoverflow.com/users/',
        example: 'CodeHelpJunkie', 
    },
];